services:
  fluentbit:
    profiles: ["scraping"]
    image: fluent/fluent-bit:3.2
    container_name: fluentbit
    ports:
    - "9880:9880"   # opzionale: solo se vuoi mandare dall'host
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    networks:
      - appnet

  kafka:
    profiles: ["kafka"]
    image: apache/kafka:4.0.1
    container_name: kafka
    networks:
        - appnet
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
    
  topic-creator:
    profiles: ["kafka"]
    image: apache/kafka:4.0.1
    depends_on:
      - kafka
    networks:
        - appnet
    entrypoint: ["/bin/bash","-lc"]
    command: |
      "
      sleep 10;
      /opt/kafka/bin/kafka-topics.sh --create --topic topBoxOffice --bootstrap-server kafka:9092
      /opt/kafka/bin/kafka-topics.sh --create --topic reviewFilm --bootstrap-server kafka:9092

      "

  # consumer per output
  kafka-dump:
    profiles: ["kafka-debug"]
    image: apache/kafka:4.0.1
    depends_on:
      - kafka
    entrypoint: ["/bin/bash","-lc"]
    command: 
      - |
        for i in {1..60}; do
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list >/dev/null 2>&1 && break
          echo "Waiting for Kafka..."
          sleep 2
        done
        echo "Starting consumer on topic topBoxOffice..."
        exec /opt/kafka/bin/kafka-console-consumer.sh \
          --bootstrap-server kafka:9092 \
          --topic reviewFilm \
          --from-beginning \
          --property print.timestamp=true \
          --property print.key=true \
          --property print.value=true
    networks:
      - appnet

  scraping:
    profiles: ["scraping"]
    container_name: scraping
    build: 
      context: ./WebScraping
    environment:
      DELAY: "0.2"
      LOOP: "true"
    networks:
      - appnet
    

networks:
  appnet:
    driver: bridge
