[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         http
    Listen       0.0.0.0
    Port         9880

[OUTPUT]
    Name    kafka
    Match   topBoxOffice
    Brokers kafka:9092
    Topics  topboxoffice
    Format json_lines

[OUTPUT]
    Name    kafka
    Match   reviewFilm
    Brokers kafka:9092
    Topics  reviewFilm
    Format json_lines

#[OUTPUT]
#    Name         stdout
#    Match        *

