[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         http
    Listen       0.0.0.0
    Port         9880

[OUTPUT]
    Name        kafka
    Match       *
    Brokers     kafka:9092
    Topics      topBoxOffice


# Opzione debug: stampa quello che riceve
###
#  [OUTPUT]
#    Name         stdout
#    Match        *
###
