[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         http
    Listen       0.0.0.0
    Port         9880

# Opzione debug: stampa quello che riceve
[OUTPUT]
    Name         stdout
    Match        *
